VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "iSupportFontPropPage"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'==================================================================================================
'iSupportFontPropPage.cls                    12/15/04
'
'           GENERAL PURPOSE:
'               Simplify the implementation of ppFont.pag for
'               the numerous controls which use it.
'
'           LINEAGE:
'               N/A
'
'==================================================================================================


Option Explicit

Public Function GetAmbientFont() As StdFont
'
End Function

Public Sub AddFonts(ByVal o As ppFont)
'
End Sub
